### PR TITLE
fix the os_family comparisons

### PR DESCRIPTION
**Pull request by martenson**

### CODE REVIEW

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
```
CRITICAL Idempotence test failed because of the following tasks:
*  => ansible-pulsar : Create Pulsar privilege separation user-owned directories
*  => ansible-pulsar : Create Pulsar config dir
```

huh that's neat.

**Comment by hexylena** [comment]
1.0.8 is available, would you mind opening the PR for the gtn @martenson ?

**Comment by martenson** [comment]
I am sorry, I am not sure what you are asking @hexylena. 1.0.8 of what?

**Comment by hexylena** [comment]
I released a new version of ansible-pulsar (version 1.0.8, previously 1.0.7) following this change.

**Comment by hexylena** [comment]
I can do the update it's ok

**Comment by martenson** [comment]
Got it, sorry, I was looking here: https://github.com/galaxyproject/ansible-pulsar/releases

**Comment by hexylena** [comment]
Ahh yeah gotcha

**Comment by martenson** [comment]
@hexylena Are they meant to correspond?

**Pull request merged**
