### PR TITLE
adding molecule testing to the playbook

### PR DESCRIPTION
**Pull request by bgruening**
Hi @natefoo,

this is our first attempt to add molecule testing to a playbook. We would welcome any comments from your side if this is a good way to proceed.

This work was done by @mtangaro from ELIXIR-IT :)  Marco you rock!

### CODE REVIEW

**Comment by bgruening** [comment]
You can see the passing tests here: https://github.com/usegalaxy-eu/ansible-pulsar/pull/4

**Comment by hexylena** [comment]
We could just do on PR, since that tests the merge commit, right? it'd cut down on testing by half?

**Comment by bgruening** [comment]
It depends on how people develop with this repo. E.g. if you use branches of this repo to test things ... in this case commits would be handy. PRs should be only tested ones imho if they are coming from a fork.

**Comment by hexylena** [comment]
Even if you use branches, we shouldn't be doing `git checkout master; git merge ...` on the command line (and thus escaping testing), we always open PRs I think. And we can enforce this by protecting master.

**Comment by hexylena** [comment]
Then it would be safe to just test PRs.

**Comment by bgruening** [comment]
:+1: let see what @natefoo  thinks. We can easily change that, ones we agree to go this route.

**Comment by hexylena** [comment]
If you like. Otherwise if he's busy, he did give me the power as one of the galaxy ansible maintainers, I think branch protections (when coupled with PR testing) is fantastic and I'm happy to make that change.

**Comment by bgruening** [comment]
Please go ahead. I see this just as a first step and imho we should get our important playbooks under testing - but I would like to have a buy-in from people that really understand whats going on here :)

Thanks, Helena!

**Comment by hexylena** [comment]
Nevermind, i thought I had that permission but just other repos, I was wrong @natefoo your presence is required.

**Review by hexylena — APPROVED** [review]
Looks good, most of this is safe, let's ship it.

**Pull request merged**
